import React from 'react'
import Head from 'next/head'
import Link from 'next/link'

const HeadComponent = () => {
  return (
    <Head>
        <title>Stitch</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}

export default HeadComponent